// blog-admin/src/app/admin/list/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

interface Post {
  id: number;
  title: string;
  content: string;
  createdAt: string;
}

export default function ListPage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const router = useRouter();

  useEffect(() => {
    // 从 localStorage 获取文章
    const storedPosts = localStorage.getItem('posts');
    if (storedPosts) {
      setPosts(JSON.parse(storedPosts));
    }
  }, []);

  const handleDelete = (id: number) => {
    const updatedPosts = posts.filter((post) => post.id !== id);
    setPosts(updatedPosts);
    localStorage.setItem('posts', JSON.stringify(updatedPosts));
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-6xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="px-4 py-6 sm:px-0">
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-3xl font-bold text-gray-900">文章列表</h1>
            <button
              onClick={() => router.push('/admin')}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200"
            >
              返回首页
            </button>
          </div>
          
          <div className="bg-white shadow rounded-lg p-6">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-semibold text-gray-900">所有文章</h2>
              <button
                onClick={() => router.push('/admin/post')}
                className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700"
              >
                发布新文章
              </button>
            </div>
            
            {posts.length === 0 ? (
              <div className="text-center py-12">
                <p className="text-gray-500">暂无文章，点击上方按钮发布第一篇文章</p>
              </div>
            ) : (
              <div className="space-y-4">
                {posts.map((post) => (
                  <div key={post.id} className="border border-gray-200 rounded-md p-4">
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="text-lg font-semibold text-gray-900">{post.title}</h3>
                      <button
                        onClick={() => handleDelete(post.id)}
                        className="px-3 py-1 text-sm text-white bg-red-600 rounded-md hover:bg-red-700"
                      >
                        删除
                      </button>
                    </div>
                    <p className="text-gray-600 mb-2">{post.content.substring(0, 100)}...</p>
                    <p className="text-sm text-gray-500">
                      {new Date(post.createdAt).toLocaleString()}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// pages/admin/list.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <div class="container mx-auto px-4 py-8">
      <header class="flex justify-between items-center mb-8">
        <h1 class="text-3xl font-bold text-gray-800">文章列表</h1>
        <div class="flex space-x-4">
          <NuxtLink
            to="/admin"
            class="bg-gray-500 text-white px-4 py-2 rounded-md hover:bg-gray-600 transition-colors"
          >
            返回首页
          </NuxtLink>
          <NuxtLink
            to="/admin/post"
            class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition-colors"
          >
            发布新文章
          </NuxtLink>
        </div>
      </header>
      <div class="bg-white rounded-lg shadow-md p-8">
        <h2 class="text-2xl font-semibold text-gray-800 mb-6">所有文章</h2>
        <div v-if="posts.length === 0" class="text-center py-12 text-gray-500">
          暂无文章，快来发布第一篇吧！
        </div>
        <div v-else class="space-y-4">
          <div
            v-for="post in posts"
            :key="post.id"
            class="border border-gray-200 rounded-md p-4 hover:shadow-sm transition-shadow"
          >
            <div class="flex justify-between items-start mb-2">
              <h3 class="text-xl font-semibold text-gray-800">{{ post.title }}</h3>
              <span class="text-sm text-gray-500">{{ formatDate(post.createdAt) }}</span>
            </div>
            <p class="text-gray-600 mb-4 line-clamp-3">{{ post.content }}</p>
            <button
              @click="deletePost(post.id)"
              class="bg-red-500 text-white px-3 py-1 rounded-md hover:bg-red-600 transition-colors text-sm"
            >
              删除
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
definePageMeta({
  middleware: 'auth'
})

const posts = useState('posts', () => [])

const deletePost = (id) => {
  if (confirm('确定要删除这篇文章吗？')) {
    posts.value = posts.value.filter(post => post.id !== id)
    if (process.client) {
      localStorage.setItem('blog_posts', JSON.stringify(posts.value))
    }
  }
}

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toLocaleString('zh-CN')
}
</script>
